name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_riverpod: ^3.0.3
  geolocator: ^14.0.2
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  lottie: ^3.3.2
  lucide_icons: ^0.257.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/weather_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/
    - assets/icons/weather_app_icon.png
